sudo: required
dist: trusty
language: ruby
rvm:
  - 2.2.5
  - 2.3.1
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3 --deployment
  - docker version
  - docker info
script:
  - bundle exec rake test
