sudo: required
language: ruby
services:
  - docker
rvm:
  - 2.2.4
  - 2.3.0
before_install:
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3 --deployment
  - docker version
  - docker info
script:
  - bundle exec rake test
